import { AdvancedCopyPluginSettings } from "./settings";

/**
 * The default settings contain four profiles:
 * - markdown_to_markdown: Convert Markdown to Markdown
 * - copy_with_backlink: Copy with backlink to source file
 * - markdown_to_html: Convert Markdown to HTML
 * - markdown_to_anki: Convert Markdown to Anki HTML
 */
export const DEFAULT_SETTINGS: AdvancedCopyPluginSettings = {
    profiles: {
        markdown_to_markdown: {
            meta: {
                id: "markdown_to_markdown",
                name: "Markdown to Markdown",
                description: "Convert Markdown to Markdown",
                cmdSelection: false,
                cmdPage: false,
                replaceGemojiShortcodes: false,
                encodeHTMLEntities: false,
                encodeHTMLEntitiesHexOnly: false,
                configVersion: 1,
                doNotUpdate: false,
            },
            templates: {
                blockquoteLine: {
                    template: "> $value\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                blockquoteWrapper: {
                    template: "$content\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                bold: {
                    template: "**$value**",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                callout: {
                    template: "> [!$type]$behavior $title\n$content\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                calloutContentLine: {
                    template: "> $value\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                codeBlock: {
                    template: "```$lang\n$value\n```\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                codeInline: {
                    template: "`$value`",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                embeddedWikilink: {
                    template: "![[$link|$text]]",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading1: {
                    template: "# $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading2: {
                    template: "## $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading3: {
                    template: "### $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading4: {
                    template: "#### $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading5: {
                    template: "##### $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading6: {
                    template: "###### $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                highlight: {
                    template: "==$value==",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                horizontalRule: {
                    template: "---\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                image: {
                    template: "![$alt]($src)",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                italic: {
                    template: "_$value_",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                lineBreak: {
                    template: "\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                link: {
                    template: "[$alt]($src)",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                listItemOrdered: {
                    template: "$indent$index. $value\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                    templateFirstChildNested: "\n$indent$index. $value\n",
                    templateLastChildNested: "",
                },
                listItemUnordered: {
                    template: "$indent-   $value\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                    templateFirstChildNested: "\n$indent-   $value\n",
                    templateLastChildNested: "",
                },
                mathBlock: {
                    template: "$$\n$value\n$$\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                mathInline: {
                    template: "$$value$",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                orderedList: {
                    template: "$content\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                paragraph: {
                    template: "$value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                paragraphNested: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                strikethrough: {
                    template: "~~$value~~",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                table: {
                    template: "$header$mdDelRow\n$content\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableRow: {
                    template: "$content|\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableHeaderCell: {
                    template: "| $content ",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableCell: {
                    template: "| $content ",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                text: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                unorderedList: {
                    template: "$content\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                wikilink: {
                    template: "[[$link|$text]]",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
            },
            extra: {
                before: "",
                after: "\n",
            },
        },
        copy_with_backlink: {
            meta: {
                id: "copy_with_backlink",
                name: "Copy with backlink",
                description: "Copy with backlink to source file",
                cmdSelection: false,
                cmdPage: false,
                replaceGemojiShortcodes: false,
                encodeHTMLEntities: false,
                encodeHTMLEntitiesHexOnly: false,
                configVersion: 1,
                doNotUpdate: false,
            },
            templates: {
                blockquoteLine: {
                    template: "> $value\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                blockquoteWrapper: {
                    template: "$content\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                bold: {
                    template: "**$value**",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                callout: {
                    template: "> [!$type]$behavior $title\n$content\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                calloutContentLine: {
                    template: "> $value\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                codeBlock: {
                    template: "```$lang\n$value\n```\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                codeInline: {
                    template: "`$value`",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                embeddedWikilink: {
                    template: "![[$link|$text]]",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading1: {
                    template: "# $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading2: {
                    template: "## $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading3: {
                    template: "### $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading4: {
                    template: "#### $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading5: {
                    template: "##### $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading6: {
                    template: "###### $value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                highlight: {
                    template: "==$value==",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                horizontalRule: {
                    template: "---\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                image: {
                    template: "![$alt]($src)",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                italic: {
                    template: "_$value_",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                lineBreak: {
                    template: "\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                link: {
                    template: "[$alt]($src)",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                listItemOrdered: {
                    template: "$indent$index. $value\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                    templateFirstChildNested: "\n$indent$index. $value\n",
                    templateLastChildNested: "",
                },
                listItemUnordered: {
                    template: "$indent-   $value\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                    templateFirstChildNested: "\n$indent-   $value\n",
                    templateLastChildNested: "",
                },
                mathBlock: {
                    template: "$$\n$value\n$$\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                mathInline: {
                    template: "$$value$",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                orderedList: {
                    template: "$content\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                paragraph: {
                    template: "$value\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                paragraphNested: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                strikethrough: {
                    template: "~~$value~~",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                table: {
                    template: "$header$mdDelRow\n$content\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableRow: {
                    template: "$content|\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableHeaderCell: {
                    template: "| $content ",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableCell: {
                    template: "| $content ",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                text: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                unorderedList: {
                    template: "$content\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                wikilink: {
                    template: "[[$link|$text]]",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
            },
            extra: {
                before: "[[$fileName]]\n",
                after: "\n",
            },
        },
        markdown_to_html: {
            meta: {
                id: "markdown_to_html",
                name: "Markdown to HTML",
                description: "Convert Markdown to HTML",
                cmdSelection: false,
                cmdPage: false,
                replaceGemojiShortcodes: true,
                encodeHTMLEntities: false,
                encodeHTMLEntitiesHexOnly: false,
                configVersion: 1,
                doNotUpdate: false,
            },
            templates: {
                blockquoteLine: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                blockquoteWrapper: {
                    template: "<blockquote>\n$content\n</blockquote>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                bold: {
                    template: "<strong>$value</strong>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                callout: {
                    template:
                        '<div class="callout callout-$type callout-closeable-$closeable callout-default-open-$default_open">\n<h2>$title</h2>\n<div>$content</div>\n</div>\n\n',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                calloutContentLine: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                codeBlock: {
                    template: "<pre><code>$value</code></pre>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                codeInline: {
                    template: "<code>$value</code>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                embeddedWikilink: {
                    template:
                        '<a href="obsidian://open?vault=$vaultName&file=$link">$text</a>',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading1: {
                    template: "<h1>$value</h1>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading2: {
                    template: "<h2>$value</h2>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading3: {
                    template: "<h3>$value</h3>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading4: {
                    template: "<h4>$value</h4>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading5: {
                    template: "<h5>$value</h5>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading6: {
                    template: "<h6>$value</h6>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                highlight: {
                    template: "<mark>$value</mark>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                horizontalRule: {
                    template: "<hr />\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                image: {
                    template: '<img src="$src" alt="$alt" />',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                italic: {
                    template: "<em>$value</em>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                lineBreak: {
                    template: "<br />",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                link: {
                    template: '<a href="$src">$alt</a>',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                listItemOrdered: {
                    template: "<li>$value</li>\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                    templateFirstChildNested: "",
                    templateLastChildNested: "",
                },
                listItemUnordered: {
                    template: "<li>$value</li>\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                    templateFirstChildNested: "",
                    templateLastChildNested: "",
                },
                mathBlock: {
                    template: "\\[$value\\]\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                mathInline: {
                    template: "\\($value\\)",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                orderedList: {
                    template: "<ol>\n$content\n</ol>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                paragraph: {
                    template: "<p>$value</p>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                paragraphNested: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                strikethrough: {
                    template: "<del>$value</del>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                table: {
                    template:
                        "<table>\n<thead>\n$header</thead>\n<tbody>\n$content</tbody>\n</table>\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableRow: {
                    template: "<tr>\n$content</tr>\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableHeaderCell: {
                    template: '<th class="text-$align">$content</th>\n',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableCell: {
                    template: '<td class="text-$align">$content</td>\n',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                text: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                unorderedList: {
                    template: "<ul>\n$content\n</ul>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                wikilink: {
                    template:
                        '<a href="obsidian://open?vault=$vaultName&file=$link">$text</a>',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
            },
            extra: {
                before: "",
                after: "\n",
            },
        },
        markdown_to_anki: {
            meta: {
                id: "markdown_to_anki",
                name: "Markdown to Anki HTML",
                description: "Convert Markdown to Anki HTML",
                cmdSelection: false,
                cmdPage: false,
                replaceGemojiShortcodes: true,
                encodeHTMLEntities: false,
                encodeHTMLEntitiesHexOnly: false,
                configVersion: 1,
                doNotUpdate: false,
            },
            templates: {
                blockquoteLine: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                blockquoteWrapper: {
                    template: "<blockquote>\n$content\n</blockquote>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                bold: {
                    template: "<strong>$value</strong>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                callout: {
                    template:
                        '<div class="callout callout-$type callout-closeable-$closeable callout-default-open-$default_open">\n<h2>$title</h2>\n<div>$content</div>\n</div>\n\n',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                calloutContentLine: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                codeBlock: {
                    template: "<pre><code>$value</code></pre>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                codeInline: {
                    template: "<code>$value</code>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                embeddedWikilink: {
                    template:
                        '<a href="obsidian://open?vault=$vaultName&file=$link">$text</a>',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading1: {
                    template: "<h1>$value</h1>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading2: {
                    template: "<h2>$value</h2>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading3: {
                    template: "<h3>$value</h3>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading4: {
                    template: "<h4>$value</h4>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading5: {
                    template: "<h5>$value</h5>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                heading6: {
                    template: "<h6>$value</h6>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                highlight: {
                    template: "<mark>$value</mark>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                horizontalRule: {
                    template: "<hr />\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                image: {
                    template: '<img src="$src" alt="$alt" />',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                italic: {
                    template: "<em>$value</em>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                lineBreak: {
                    template: "<br />",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                link: {
                    template: '<a href="$src">$alt</a>',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                listItemOrdered: {
                    template: "<li>$value</li>\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                    templateFirstChildNested: "",
                    templateLastChildNested: "",
                },
                listItemUnordered: {
                    template: "<li>$value</li>\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                    templateFirstChildNested: "",
                    templateLastChildNested: "",
                },
                mathBlock: {
                    template:
                        '<anki-mathjax block="true">$value</anki-mathjax>\n\n',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                mathInline: {
                    template: "<anki-mathjax>$value</anki-mathjax>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                orderedList: {
                    template: "<ol>\n$content\n</ol>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                paragraph: {
                    template: "<p>$value</p>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                paragraphNested: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                strikethrough: {
                    template: "<del>$value</del>",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                table: {
                    template:
                        "<table>\n<thead>\n$header</thead>\n<tbody>\n$content</tbody>\n</table>\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableRow: {
                    template: "<tr>\n$content</tr>\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableHeaderCell: {
                    template: '<th class="text-$align">$content</th>\n',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                tableCell: {
                    template: '<td class="text-$align">$content</td>\n',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                text: {
                    template: "$value",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                unorderedList: {
                    template: "<ul>\n$content\n</ul>\n\n",
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
                wikilink: {
                    template:
                        '<a href="obsidian://open?vault=$vaultName&file=$link">$text</a>',
                    templateFirstOfType: "",
                    templateLastOfType: "",
                    templateFirstChild: "",
                    templateLastChild: "",
                },
            },
            extra: {
                before: "",
                after: "\n",
            },
        },
    },
};
